### ISSUE TITLE
Add Addin to Cake Website

### ISSUE THREAD

**Issue by gep13** [graph-uk/Cake.XmlConfigStructureBuilder#3]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by gep13** [comment]
@jincod just wanted to follow up with this issue.  Do you have any questions?  Thanks.

**Comment by jincod** [comment]
Hi @gep13 

Sorry for late answer. Better Late Than Never😀

I've made PR https://github.com/cake-build/website/pull/486 finally😀

Sorry for late again.

**Comment by gep13** [comment]
@jincod no need to apologise!  Thanks for getting this done 👍
